### ISSUE TITLE
Transparency With Masks

### ISSUE THREAD

**Issue by EvieMae** [Lexicality/stencil-tutorial#1]
Im using this as the base for the code:
https://github.com/Lexicality/stencil-tutorial/blob/master/lua/stencil_tutorial/10_2d_stencils.lua

Instead of DrawPoly, Im using surface.DrawTexturedRect() with a texture like this, 
![image](https://user-images.githubusercontent.com/24654131/89138848-cfd3c780-d534-11ea-9c74-bc2275f89b5f.png)
I tried making the circle white, and having a white bg and black circle (and inverted as well) and it would just be a square.
![image](https://user-images.githubusercontent.com/24654131/89138871-e417c480-d534-11ea-983d-24e13ddff4b0.png)

I did try and have a look online before posting, I will appreciate any help, and if you're busy or its not possible, that's okay. 
Thank you

**Comment by Lexicality** [comment]
Hi, sorry for the delay in seeing this.
If I remember correctly, gmod has no way to write directly to the stencil buffer which means you can't write data - only shapes and in this case the shape you're writing is the square texture.
Also, you have gradient in your texture which very likely wouldn't do what you want because stencil operations are always on or off.

I **think** this the example on [render.SetWriteDepthToDestAlpha](https://wiki.facepunch.com/gmod/render.SetWriteDepthToDestAlpha) does what you want, but I've never used it myself. I'll have a look later.

**Comment by EvieMae** [comment]
![image](https://i.gyazo.com/ea87740d53dfb5d417719ddef1ed3305.gif)
Thank you So much for that

**Comment by Lexicality** [comment]
You're welcome
